<?php

namespace app\index\controller;

use app\common\controller\Frontend;

class Template extends Frontend
{
  protected $noNeedLogin = ['*'];
  protected $noNeedRight = ['*'];
  protected $layout = '';

  public function _initialize()
  {
    parent::_initialize(); // TODO: Change the autogenerated stub
  }

  public function template1()
  {
    return $this->view->fetch();
  }
}
